import { NextRequest, NextResponse } from 'next/server';
import {
  getModelInfo,
  getDelegate,
  buildSearchWhere,
  sanitizeRecord,
  coerceValue,
  isAutoGeneratedField,
} from '@/lib/database-explorer';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ model: string }> }
) {
  try {
    const { model: modelName } = await params;
    const model = getModelInfo(modelName);
    if (!model) {
      return NextResponse.json(
        { error: 'Not Found', message: 'Model not found' },
        { status: 404 }
      );
    }

    const delegate = getDelegate(modelName);
    if (!delegate) {
      return NextResponse.json(
        { error: 'Bad Request', message: 'Model not accessible' },
        { status: 400 }
      );
    }

    const { searchParams } = new URL(request.url);
    const page = Math.max(1, parseInt(searchParams.get('page') || '1', 10));
    const limit = Math.min(Math.max(1, parseInt(searchParams.get('limit') || '50', 10)), 100);
    const search = searchParams.get('search') || '';
    const sortBy = searchParams.get('sortBy') || model.idField;
    const sortOrder = searchParams.get('sortOrder') === 'asc' ? 'asc' : 'desc';
    const skip = (page - 1) * limit;

    const validSort = model.scalarFields.some((f) => f.name === sortBy);
    const where = buildSearchWhere(model, search);

    const [records, total] = await Promise.all([
      delegate.findMany({
        where,
        skip,
        take: limit,
        orderBy: validSort ? { [sortBy]: sortOrder } : undefined,
      }),
      delegate.count({ where }),
    ]);

    return NextResponse.json({
      records: records.map((r) => sanitizeRecord(r, model)),
      schema: model,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error('Failed to fetch records:', error);
    return NextResponse.json(
      { error: 'Internal Server Error', message: 'Failed to fetch records' },
      { status: 500 }
    );
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ model: string }> }
) {
  try {
    const { model: modelName } = await params;
    const model = getModelInfo(modelName);
    if (!model) {
      return NextResponse.json(
        { error: 'Not Found', message: 'Model not found' },
        { status: 404 }
      );
    }
    if (model.isProtected) {
      return NextResponse.json(
        { error: 'Forbidden', message: 'This model is read-only' },
        { status: 403 }
      );
    }

    const delegate = getDelegate(modelName);
    if (!delegate) {
      return NextResponse.json(
        { error: 'Bad Request', message: 'Model not accessible' },
        { status: 400 }
      );
    }

    const body = await request.json();
    const data: Record<string, unknown> = {};

    for (const field of model.scalarFields) {
      if (isAutoGeneratedField(field)) continue;
      if (field.isSensitive) continue;
      if (body[field.name] !== undefined) {
        data[field.name] = coerceValue(body[field.name], field.type, field.isRequired);
      }
    }

    const record = await delegate.create({ data });
    return NextResponse.json({ record: sanitizeRecord(record, model) }, { status: 201 });
  } catch (error) {
    console.error('Failed to create record:', error);
    const message = error instanceof Error ? error.message : 'Failed to create record';
    return NextResponse.json(
      { error: 'Internal Server Error', message },
      { status: 500 }
    );
  }
}
